# Generated by Django 2.2 on 2019-04-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_employmentauth'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='emp_auth',
        ),
        migrations.AddField(
            model_name='review',
            name='emp_auth',
            field=models.ManyToManyField(to='users.EmploymentAuth'),
        ),
    ]
