# Generated by Django 2.2 on 2019-04-26 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0010_employmentauth'),
        ('review', '0002_auto_20190426_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='emp_auth',
        ),
        migrations.CreateModel(
            name='CompanyEmploymentAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=False)),
                ('employment_auth',
                 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.EmploymentAuth')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='review.Review')),
            ],
        ),
    ]
