# Generated by Django 2.2 on 2019-10-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='coach_listing_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
