# Generated by Django 2.2 on 2019-10-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usertype_coach_listing_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.FileField(blank=True, default='981fa136-adc0-4b26-89bf-c1c4bb56af6f.png', null=True, upload_to=''),
        ),
    ]
