# Generated by Django 2.2 on 2019-04-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_profile_emp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentstatus',
            name='value',
            field=models.CharField(default='N/A', max_length=20),
        ),
    ]
