# Generated by Django 2.2 on 2019-04-26 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0008_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='star',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5),
                                                                         django.core.validators.MinValueValidator(0)]),
        ),
    ]
