# Generated by Django 2.2 on 2019-08-06 06:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0028_auto_20190805_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_login',
        ),
    ]
