# Generated by Django 2.2 on 2019-08-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0029_remove_profile_first_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(
                choices=[(0, 'NONE'), (1, 'PUBLIC'), (2, 'STUDENT'), (3, 'ALUMNI'), (4, 'CAREER SERVICE')], default=0),
        ),
    ]
