# Generated by Django 2.2 on 2019-09-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_auto_20190911_1158'),
        ('users', '0034_feedback_created_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmploymentAuth',
        ),
    ]
