# Generated by Django 2.2 on 2019-09-16 20:21
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20190916_1253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
