# Generated by Django 2.2 on 2019-09-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20190916_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_photo_custom',
            new_name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_photo_social',
        ),
    ]
