# Generated by Django 2.2 on 2019-09-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_user_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='from_demo_account',
            field=models.BooleanField(default=False),
        ),
    ]
