# Generated by Django 2.2 on 2019-09-28 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
