# Generated by Django 2.2 on 2019-09-28 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_remove_user_user_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='type',
            new_name='user_type',
        ),
    ]
