# Generated by Django 2.2 on 2019-09-29 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20190928_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='alumni_listing_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertype',
            name='blog_creation_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertype',
            name='college_specific_metrics_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usertype',
            name='event_creation_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
