# Generated by Django 2.2 on 2019-09-30 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_auto_20190928_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_update_completed',
            field=models.BooleanField(default=False),
        ),
    ]
