# Generated by Django 2.2 on 2019-09-30 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_user_profile_update_completed'),
    ]

    def update_profile_update_completed(apps, schema_editor):
        User = apps.get_model('users', 'User')
        users = User.objects.all()
        for user in users:
            if user.user_type is not None and user.user_type.name != 'Undefined':
                user.signup_flow_completed = True
                user.save()

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_update_completed',
            new_name='signup_flow_completed',
        ),
        migrations.RunPython(update_profile_update_completed, reverse_code=migrations.RunPython.noop)
    ]
