# Generated by Django 2.2 on 2019-10-09 22:41

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_auto_20191009_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnihomepage',
            name='banners',
        ),
        migrations.RemoveField(
            model_name='alumnihomepage',
            name='secondary_banners',
        ),
        migrations.RemoveField(
            model_name='alumnihomepage',
            name='social_accounts',
        ),
        migrations.AddField(
            model_name='alumnihomepage',
            name='additional_banners',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumnihomepage',
            name='header_banners',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumnihomepage',
            name='social_media_accounts',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
