# Generated by Django 2.2 on 2019-10-11 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_auto_20191009_1541'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlumniHomePage',
        ),
    ]
