# Generated by Django 2.1.5 on 2019-04-23 05:46

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date'),
        ),
    ]
