# Generated by Django 2.1.5 on 2019-02-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobapps', '0002_googlemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='isRejected',
            field=models.BooleanField(default=False),
        ),
    ]
