# Generated by Django 2.2 on 2019-05-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobapps', '0027_googlemail_app_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='rejected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
