# Generated by Django 2.2 on 2019-05-28 21:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobapps', '0031_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[
                django.core.validators.RegexValidator(
                    message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                    regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
