# Generated by Django 2.2 on 2019-08-21 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0034_auto_20190807_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='applicationStatus',
            new_name='application_status',
        ),
        migrations.RenameField(
            model_name='statushistory',
            old_name='applicationStatus',
            new_name='application_status',
        ),
    ]
