# Generated by Django 2.2 on 2019-08-21 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0035_auto_20190821_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='googlemail',
            old_name='msgId',
            new_name='msg_id',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='msgId',
            new_name='msg_id',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='application_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobapplication_application_status', to='jobapps.ApplicationStatus'),
        ),
        migrations.AlterField(
            model_name='statushistory',
            name='application_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statushistory_application_status', to='jobapps.ApplicationStatus'),
        ),
    ]
