# Generated by Django 2.2 on 2019-08-21 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0036_auto_20190821_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='companyObject',
            new_name='company_object',
        ),
    ]
