# Generated by Django 2.2 on 2019-08-21 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0037_auto_20190821_0645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='applyDate',
            new_name='apply_date',
        ),
    ]
