# Generated by Django 2.2 on 2019-08-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0038_auto_20190821_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='isDeleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='isRejected',
            new_name='is_rejected',
        ),
    ]
