# Generated by Django 2.2 on 2019-09-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0040_auto_20190916_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatus',
            name='rejectable',
            field=models.BooleanField(default=True),
        ),
    ]
