# Generated by Django 2.2 on 2019-08-03 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('college', '0002_import_college_data_from_json'),
    ]

    operations = [
    ]
