# Generated by Django 2.2 on 2019-10-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegecoach',
            name='summary_photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
