# Generated by Django 2.2 on 2019-08-07 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0033_auto_20190807_0847'),
        ('college', '0004_auto_20190804_0034'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Major',
        ),
    ]
