# Generated by Django 2.2 on 2019-10-11 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_collegecoach_summary_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.College'),
        ),
    ]
