# Generated by Django 2.2 on 2019-10-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_auto_20190924_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
