# Generated by Django 2.2 on 2019-10-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0006_homepagevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagevideo',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
