# Generated by Django 2.2 on 2019-10-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0007_homepagevideo_is_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='jobhax_domain',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
