# Generated by Django 2.2 on 2019-10-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0008_college_jobhax_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='jobhax_subdomain',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
