# Generated by Django 2.2 on 2019-10-15 02:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_college_jobhax_subdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.College'),
        ),
        migrations.AlterField(
            model_name='homepagevideo',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.College'),
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='college.College')),
            ],
        ),
    ]
