# Generated by Django 2.2 on 2019-10-15 17:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0010_auto_20191014_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepagevideo',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='homepagevideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 10, 15, 17, 7, 19, 959516, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
