# Generated by Django 2.2 on 2019-10-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
