# Generated by Django 2.2 on 2019-10-14 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_is_rejected'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-updated_at']},
        ),
    ]
