# Generated by Django 2.2 on 2019-04-29 20:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0007_auto_20190429_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='snippet',
            field=models.CharField(max_length=400, null=True,
                                   validators=[django.core.validators.MinLengthValidator(250)]),
        ),
    ]
