# Generated by Django 2.2 on 2019-08-21 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190807_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='snippet',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
