# Generated by Django 2.2 on 2019-09-28 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190826_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_public',
        ),
    ]
