# Generated by Django 2.2 on 2019-08-08 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20190808_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='view_count',
        ),
    ]
