# Generated by Django 2.2 on 2019-10-11 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0005_auto_20191011_0938'),
        ('event', '0002_auto_20191009_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='college.College'),
        ),
    ]
