# Generated by Django 2.2 on 2019-08-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20190808_0940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='event_date_start',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
