# Generated by Django 2.2 on 2019-10-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20191013_2140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-event_date_start']},
        ),
    ]
