# Generated by Django 2.2 on 2019-09-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_auto_20190826_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_public',
        ),
    ]
