# Generated by Django 2.2 on 2019-09-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0048_auto_20190929_2057'),
        ('event', '0009_auto_20190928_1516'),
    ]

    def migrate_user_types(apps, schema_editor):
        UserType = apps.get_model('users', 'UserType')
        Event = apps.get_model('event', 'Event')
        events = Event.objects.all()
        for e in events:
            if e.host_user is None or e.host_user.user_type is None or e.host_user.user_type.name == 'Undefined' \
                    or e.host_user.user_type.name == 'Public':
                e.user_types.add(UserType.objects.get(name__iexact='Public'))
            elif e.host_user.user_type.name == 'Student':
                e.user_types.add(UserType.objects.get(name__iexact='Student'))
            elif e.host_user.user_type.name == 'Alumni':
                e.user_types.add(UserType.objects.get(name__iexact='Alumni'))
            else:
                e.user_types.add(UserType.objects.get(name__iexact='Public'))

    operations = [
        migrations.AddField(
            model_name='event',
            name='user_types',
            field=models.ManyToManyField(to='users.UserType'),
        ),
        migrations.RunPython(migrate_user_types, reverse_code=migrations.RunPython.noop)
    ]
