# Generated by Django 2.1.5 on 2019-02-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobapps', '0003_jobapplication_isrejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlemail',
            name='msgId',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
