# Generated by Django 2.1.5 on 2019-02-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobapps', '0004_googlemail_msgid'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='isDeleted',
            field=models.BooleanField(default=False),
        ),
    ]
