# Generated by Django 2.1.5 on 2019-04-23 06:39

from django.db import migrations

from utils.clearbit_company_checker import get_company_detail


class Migration(migrations.Migration):

    def populate_data(apps, schema_editor):
        Company = apps.get_model('company', 'Company')
        for c in Company.objects.all():  
            cd = get_company_detail(c.company)  
            if cd is not None:
                c.cb_name=cd['name']
                c.cb_company_logo=cd['logo']
                c.cb_domain=cd['domain']
                c.save()
                
    dependencies = [
        ('jobapps', '0015_auto_20190422_2356'),
    ]

    operations = [
        migrations.RunPython(populate_data, reverse_code=migrations.RunPython.noop)
    ]
