# Generated by Django 2.2 on 2019-04-26 01:24

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobapps', '0016_prepopulate_company_and_position_tables2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplicationnote',
            name='update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
