# Generated by Django 2.2 on 2019-04-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0017_auto_20190426_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatus',
            name='default',
            field=models.BooleanField(default=False),
        )
    ]
