# Generated by Django 2.2 on 2019-04-26 05:59

from django.db import migrations


class Migration(migrations.Migration):

    def populate_data(apps, schema_editor):
        JobApplication = apps.get_model('jobapps', 'JobApplication')
        Source = apps.get_model('jobapps', 'Source')
        for j in JobApplication.objects.all():
            if j.app_source is None:
                source = Source.objects.get(value="N/A")
                j.app_source = source
                j.save()

    dependencies = [
        ('jobapps', '0021_remove_jobapplication_source'),
    ]

    operations = [
        migrations.RunPython(populate_data, reverse_code=migrations.RunPython.noop)
    ]
