# Generated by Django 2.2 on 2019-04-30 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapps', '0024_source_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPostDetail',
        ),
    ]
