# Generated by Django 2.2 on 2019-05-28 19:55

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('jobapps', '0028_jobapplication_rejected_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
