# Generated by Django 2.2 on 2019-10-03 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('position', '0001_initial'),
        ('jobapps', '0002_auto_20191003_1652'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='emp_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.EmploymentStatus'),
        ),
        migrations.AddField(
            model_name='review',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='position.JobPosition'),
        ),
        migrations.AddField(
            model_name='review',
            name='source_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobapps.SourceType'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyemploymentauth',
            name='employment_auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.EmploymentAuth'),
        ),
        migrations.AddField(
            model_name='companyemploymentauth',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Review'),
        ),
    ]
