# Generated by Django 2.2 on 2019-09-11 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_auto_20190812_2227'),
    ]

    def move_data(apps, schema_editor):
        UsersEmploymentAuth = apps.get_model('users', 'EmploymentAuth')
        ReviewEmploymentAuth = apps.get_model('review', 'EmploymentAuth')
        for ue in UsersEmploymentAuth.objects.all():
            re = ReviewEmploymentAuth()
            re.value = ue.value
            re.save()

    operations = [
        migrations.CreateModel(
            name='EmploymentAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20)),
            ],
        ),
        migrations.RunPython(move_data, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='companyemploymentauth',
            name='employment_auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.EmploymentAuth'),
        ),
    ]
