# Generated by Django 2.2 on 2019-08-07 05:15

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0009_auto_20190807_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='header_image',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(
                location='/Users/hellsayenci/Documents/web_projects/JobHax/JobHaxBackend/JH_RestAPI/media/blog'),
                                   upload_to=''),
        ),
    ]
