# Generated by Django 2.2 on 2019-08-07 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190807_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_html',
        ),
    ]
