# Generated by Django 2.2 on 2019-08-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190807_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='header_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
