# Generated by Django 2.2 on 2019-08-05 21:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('utils', '0002_country_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='states',
        ),
    ]
