# Generated by Django 2.1.5 on 2019-01-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_gmnail_read_ok',
            new_name='is_gmail_read_ok',
        ),
    ]
