# Generated by Django 2.2 on 2019-05-02 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0015_auto_20190502_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key',
            field=models.TextField(null=True),
        ),
    ]
