# Generated by Django 2.2 on 2019-05-02 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20190502_0408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='change_password_key',
            new_name='forgot_password_key',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='change_password_key_expires',
            new_name='forgot_password_key_expires',
        ),
    ]
