# Generated by Django 2.2 on 2019-05-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0018_auto_20190502_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activation_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='forgot_password_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='forgot_password_key_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='key_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
