# Generated by Django 2.2 on 2019-05-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0019_auto_20190502_0649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_updated',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
