# Generated by Django 2.2 on 2019-08-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0023_profile_synching'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(default=0),
        ),
    ]
