# Generated by Django 2.2 on 2019-08-04 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('college', '0004_auto_20190804_0034'),
        ('company', '0002_auto_20190429_2110'),
        ('position', '0003_auto_20190510_2037'),
        ('users', '0025_remove_profile_linkedin_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='college.College'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='company.Company'),
        ),
        migrations.AddField(
            model_name='profile',
            name='grad_year',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='position.JobPosition'),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='college.Major'),
        ),
    ]
