# Generated by Django 2.2 on 2019-08-07 05:33

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20190806_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo_custom',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/Users/hellsayenci/Documents/web_projects/JobHax/JobHaxBackend/JH_RestAPI/media/user'), upload_to=''),
        ),
    ]
