# Generated by Django 2.2 on 2019-08-07 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20190807_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo_custom',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
