# Generated by Django 2.2 on 2019-09-27 20:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_import_country_data_from_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='question')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='date')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
            ],
            options={
                'verbose_name': 'feedback question',
                'verbose_name_plural': 'feedback questions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=250, verbose_name='value')),
                ('custom_input', models.BooleanField(default=False, verbose_name='custom input')),
                ('pos', models.SmallIntegerField(default='0', verbose_name='position')),
                ('feedback_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='utils.FeedbackQuestion')),
            ],
            options={
                'verbose_name': 'feedback question item',
                'verbose_name_plural': 'feedback question items',
                'ordering': ['pos'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.CharField(blank=True, max_length=250, verbose_name='user input')),
                ('ip', models.GenericIPAddressField(verbose_name="user's IP")),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='utils.FeedbackQuestionItem', verbose_name='answered item')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.FeedbackQuestion', verbose_name='feedback question')),
            ],
            options={
                'verbose_name': 'feedback answer',
                'verbose_name_plural': 'feedback answers',
            },
        ),
    ]
