# Generated by Django 2.2 on 2019-09-28 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_auto_20190927_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackanswer',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='utils.FeedbackQuestionItem', verbose_name='answered item'),
        ),
    ]
