# Generated by Django 2.1.5 on 2019-04-22 23:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobApplication',
            new_name='JobPosition',
        ),
        migrations.RenameField(
            model_name='jobposition',
            old_name='jobTitle',
            new_name='job_title',
        ),
    ]
